Implemented mock classes
vdraganic21/IndoorLocalization pull request #15
Opened 2024-12-10 15:17 UTC by lbrlekovi20

Implemented mock classes for mock data and the ability to switch between using mock data and actual database data using appsettings.json. Now the REST service funcitonalities are fully testable.

2024-12-10 17:11 UTC, vdraganic21 requested changes
Implementation seems fine. Program runs.
I requested some changes to be made, please consider them.
Keep up the good work with other repositories.
Make the changes and I'll approve the PR! 😃

2024-12-10 17:11 UTC, vdraganic21 commented on RESTservice-API/Data/MockPositionHistoryRepository.cs
> +            // Initialize some mock data
Remove comment.

2024-12-10 17:11 UTC, vdraganic21 commented on RESTservice-API/appsettings.json
> +  "UseMockData": true, // Set to true for mock data, false for real database
A nice way to quickly change between mock mode and actual database usage. 👍 
Be careful to not overcomplicate things with appsettings in the future.

2024-12-10 17:11 UTC, vdraganic21 commented on RESTservice-API/Program.cs
> +// Register the services based on whether to use mock data or the real database
Remove comments.

2024-12-10 17:11 UTC, vdraganic21 commented on RESTservice-API/Program.cs
> +    builder.Services.AddDbContext<ApplicationDbContext>(options =>
Consider refactoring these blocks of code into functions.

2024-12-10 17:11 UTC, vdraganic21 commented on RESTservice-API/Interfaces/PositionHistoryRepository.cs
> +            // Ensure that this method returns IEnumerable<PositionHistory>
Remove comments.

2024-12-10 17:11 UTC, vdraganic21 commented on RESTservice-API/Controllers/AssetsController.cs
Controller now uses repository for data access. Seems fine.

2024-12-13 15:31 UTC, vdraganic21 approved these changes
lgtm

2024-12-13 16:14 UTC, aslavicek21 approved these changes
Great work; approved.

2024-12-13 16:14 UTC, merged